version: '3'
services:
  first_app:
    container_name: kimyo-uz
    build: .
    restart: always
    ports:
      - "8003:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/simple_db
      SPRING_DATASOURCE_USERNAME: simple_user
      SPRING_DATASOURCE_PASSWORD: root
    depends_on:
      - postgres
      - redis-server
  postgres:
    container_name: postgres-db
    image: "postgres:15"
    restart: always
    ports:
      - "5434:5432"
    environment:
      POSTGRES_DB: simple_db
      POSTGRES_USER: simple_user
      POSTGRES_PASSWORD: root

  redis-server:
    hostname: redis
    container_name: redis-db
    image: 'redis'
    ports:
      - "6379:6379"